### ISSUE TITLE
Game Design Ideas

### ISSUE THREAD

**Issue by late-in-autumn** [late-in-autumn/Social-Mobile-Games-Code-Benders#1]
Though we most settled to start with Angry Birds, we need to make the core business logic different.

Please share your ideas in the comments, or via this document: https://docs.google.com/document/d/1oSfjbW0MbLT-8LJgFO8STvqsNLYwq-zzAIQ_EOXvU98/edit?usp=sharing

P.S. GitHub has a max assignee limit of 10, but technically everyone is assigned. Sorry @Ronitlal I have to notify you here.

**Comment by liling10822** [comment]
stones hit the eggs, the blocks can be the cotton stuff to protect the eggs

**Comment by late-in-autumn** [comment]
To expand on the idea of @liling10822 we can have a cat figure on each side. This is a play on the fact that cats like to destroy eggs in birds' nests. However I am not sure if this has negative cultural implications.

**Comment by asthas** [comment]
I feel the target can be alien objects and bullets can hit these objects

**Comment by niya11** [comment]
Spidey war: spiders shooting lil spidermen to destroy the web/blocks and save their radioactive elements :P  
or 
Pirates war: two pirates shooting sea creatures at each other to destroy the ship and save the treasure
 
Totally unrelated but check out this game it looks soooo cooool: https://www.youtube.com/watch?v=92rWWaspoFI

**Comment by adink94** [comment]
Winter Themed Battle : Each Team will attempt to wreck the other Team's Snowman.

The Target could be the Snowmen and the projectiles could be modeled as Snow balls.
Can also extend this idea to support our requirement of having various projectiles (Like we can have Fire Ball, Dirt Ball, Snow Ball etc..)

**Comment by bzhu36** [comment]
Bonfire Theme: Each side will try to protect bonfires that symbolize their civilization.

Projectiles being fired can be water balloons and others can have distinct features (ice cubes, sand, fire blanket, weather inducing ammo, etc)

Walls can be a variety of walls mud, stone, steel, ice etc.
